package view;

import java.awt.BorderLayout;
import java.awt.GridLayout;

/**
 * Classe qui construit la fenêtre d'instruction. Elle appelle InstructionsPanel pour déssiner les noeuds, les robots, les arrêtes possibles.
 * @author De Sousa Jérémy
 */
public class InstructionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form InstructionsFrame
     */
    public InstructionsFrame() {
        initComponents();
        InstructionsPanel instructionsPanel = new InstructionsPanel();
        jPanel1.setVisible(true);
        this.jPanel1.add(instructionsPanel);
        instructionsPanel.repaint();
        setTitle("Instructions");
        this.setSize(800, 500);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Instruction");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Création du graph : \nPour créer le graph, il vous suffit de cliquer sur la carte pour y ajouter un noeud.\nAvant de cliquer sur la carte, vous pouvez choisir le type de noeud à ajouter (normal ou incendié).\n\nPour ajouter une arrête, il faut d'abord selectionner le noeud de départ en cliquant dessus, puis le noeud d'arrivé en cliquant dessus.\n\nEn cas de mauvaise manipulation, vous pouvez cliquer sur le bouton \"back\" pour annuler la dernière action.\n\nLe bouton reset permet de remettre à zéro la simulation : supprimer le graph et les robots et incendies.\n\nEn appuyant sur le bouton play, vous allez lancer la simulation. \n\nVous pourrez alors ajouter les différents robots en cochant le robot désiré.\n\nVous pouvez également ajouter un incendie avec une intensité comprise entre 1 et 20.\nSi la valeur entrée n'est pas valide, l'incendie prend la valeur par défaut (15).");
        jTextArea1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
